const express = require("express");
const {register,login,verifyOtp,checkEmail,forgotPassword,likeDoctor,unlikeDoctor,uploadPatientPicture} = require("../Controller/Patient");
const router = express.Router();
router.post("/register",register);
router.post("/login",login);
router.post("/verify",verifyOtp);
router.post("/checkEmail",checkEmail);
router.put("/forgot",forgotPassword);
router.post("/like",likeDoctor);
router.post("/unlike",unlikeDoctor);
router.post("/uploadPicture",uploadPatientPicture);
module.exports = router;